DELETE FROM check_date;

INSERT INTO check_date (date_code,       -- 날짜코드 = integer
                        year_month_day,  -- 연월일  = date
						month_code)      -- 월별코드 = integer
SELECT
    DATE_FORMAT(date, '%Y%m%d'),
    DATE_FORMAT(date, '%Y-%m-%d'),
    MONTH(date) as month_code
FROM (
    SELECT DATE('2024-01-01') + INTERVAL (t4*1000 + t3*100 + t2*10 + t1) DAY AS date
    FROM
        (SELECT 0 AS t1 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) thousands,
        (SELECT 0 AS t2 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) hundreds,
        (SELECT 0 AS t3 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) tens,
        (SELECT 0 AS t4 UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) ones
) AS date_sequence
WHERE date BETWEEN '2024-01-01' AND '2024-12-31';

SELECT * FROM check_date
     ORDER BY date_code;
